Final Merge of Push Contracts 2.5 Dev New structure and tests
ethereum-push-notification-service/push-smart-contracts pull request #249
Opened 2024-01-05 11:36 UTC by zaryab2000

This PR is a mega merge of the new structure of the push contracts along with other files such as tests, interfaces, libraries etc.

Some of the key updates in this PR are as follows:

- Test Migration of Hardhat to Foundry
- Fuzz tests for Core and Staking
- Interfaces for Core, Comm, Staking contracts
- Inclusion of libraries and Separate files for Custom Data Type handling/management

2024-01-09 11:52 UTC, 0xNilesh requested changes

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SendingNotifications/SendNotifs.t.sol
> +    bytes constant _testChannelIdentity = bytes("test-channel-hello-world");
this variable is used in all 3 files of comm tests, and in BasePushCoreTest.t.sol
If it's getting used in whole test codebase, then it's better to put it in BaseTest itself

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SendingNotifications/SendNotifs.t.sol
> +        //User can no longer send notifs to themselves
this test is missed

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SendingNotifications/SendNotifsViaSig.t.sol
> +    function getStructHash(SendNotif memory _sendNotif) internal pure returns (bytes32) {
There could be a BasePushCommTest file that could have these extra helper fn and variables

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SendingNotifications/SendNotifsViaSig.t.sol
> +    struct SendNotif {
this one in BasePushCommTest as well

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SendingNotifications/SendNotifsViaSig.t.sol
> +    function getDomainSeparator() public returns (bytes32) {
this one in BasePushCommTest as well

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +    event Subscribe(address indexed channel, address indexed user);
these events should've been added in test/utils/Events.sol file under CommEvents

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +    event Unsubscribe(address indexed channel, address indexed user);
this too

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +import "forge-std/console.sol";
unused import

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +    function testFail_WhenMaliciousUserReplaysA712Signature() public whenUserSubscribesWith712Sig {
is this issue of expectRevert remaining?
and if not, then I think we should remove testFail and use expectRevert, as it's the case in all tests

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +    function test_WhenAnExpired712SignatureIsPassed() public whenUserSubscribesWith712Sig {
as this is a test that has expectRevert, this should've been named as test_Revertwhen_
It's good to maintain uniformity across all tests

It's the case with few tests in this file, all should be changed accordingly

2024-01-09 11:52 UTC, 0xNilesh commented on test/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
> +    function getStructHash(
these can be put in BasePushCommTest file as well

2024-01-09 11:53 UTC, 0xNilesh requested changes
When I run `forge test`,
It's showing these errors

<img width="924" alt="image" src="https://github.com/ethereum-push-notification-service/push-smart-contracts/assets/54444545/5d06f48f-5cc5-4579-9b65-150e2335c4fe">

2024-01-10 07:00 UTC, Zartaj0 commented on contracts/interfaces/IPushCoreStaking.sol
> +import { CoreTypes } from "../libraries/DataTypes.sol";
Unused import

2024-01-10 07:08 UTC, Zartaj0 approved these changes

2024-01-10 12:26 UTC, merged

2024-01-10 12:26 UTC, zaryab2000 commented
Merged this branch finally to pushContracts_2.5_dev branch.