Solved the verification Bug and migrated the test
ethereum-push-notification-service/push-smart-contracts pull request #259
Opened 2024-01-10 12:54 UTC by Zartaj0

This PR contains changes for https://github.com/ethereum-push-notification-service/push-smart-contracts/issues/253

2024-01-11 12:21 UTC, 0xNilesh requested changes
Few pointers:
1> can you include test cases for checking verifiedBy variable change in the fn (if correct address is populating in it or not)
2> if you can create separate files for verifyChannel and unverifyChannel, and even for getChannelVerification in this ChannelVerification directory, it'd be better
3> Ig tests for batchVerification will come in admin related test suits, if that's the case, then it's alright

2024-01-12 05:38 UTC, Zartaj0 commented
> Few pointers: 1> can you include test cases for checking verifiedBy variable change in the fn (if correct address is populating in it or not) 2> if you can create separate files for verifyChannel and unverifyChannel, and even for getChannelVerification in this ChannelVerification directory, it'd be better 3> Ig tests for batchVerification will come in admin related test suits, if that's the case, then it's alright

1. Good catch, done the changes. 
2. Made separate folders for both `verify` and `unverify`. I think `getChannelVerification` doesn't require a separate file as it is a view function only, which is being tested in both the mentioned test files. 
3. Admin Action test files are mainly for the independent setter functions, that don't come under any other functionality ending up being untested.

2024-01-12 12:27 UTC, 0xNilesh approved these changes
LGTM

2024-01-15 04:14 UTC, zaryab2000 commented
Couple of pointers found in the review of this PR:

1. The tree files need to be more specific and detailed for every test. For instance:

- The current tree files for verifications, doesn't include the event emission tests at all.
- Verify channel tree files doesn't specifically include the **_onlyActivatedChannels_** modifier related tests
- _As a result, these test cases are also not visible in the actual test files_
**Note:** Devote more time in designing/documenting tree files to ensure no branch is missing _(even for instances where the test is supposed to pass)_

2. Naming conventions of the tests can be made more readable for lengthy test names. For instances

Use `test_WhenChecked_TheVerificationStatusFor_AdminOrZeroAddress` instead of `test_WhenCheckedTheVerificationStatusForAdminOrZeroAddress`

@Zartaj0

2024-01-15 04:40 UTC, zaryab2000 requested changes

2024-01-15 04:40 UTC, zaryab2000 commented on test/PushCore/unit_tests/ChannelVerificationUnverification/ChannelVerification/ChannelVerification.t.sol
> +        changePrank(actor.admin);
This line might be redundant. @Zartaj0

2024-01-15 04:40 UTC, zaryab2000 commented on test/PushCore/unit_tests/ChannelVerifyTag/ChannelUnverification/ChannelUnverification.t.sol
> +        changePrank(actor.admin);
This line might be redundant @Zartaj0

2024-01-15 06:20 UTC, zaryab2000 approved these changes

2024-01-15 06:21 UTC, merged