added migration and test
ethereum-push-notification-service/push-smart-contracts pull request #379
Opened 2024-06-04 12:06 UTC by Zartaj0

2024-06-07 10:47 UTC, 0xNilesh reviewed
Functionality wise LGTM!

2024-06-07 10:47 UTC, 0xNilesh commented on contracts/PushCore/PushCoreV3.sol
> +    function migaretAddresToBytes32(address[] calldata _channels) external whenPaused {
migrateAddressToBytes32 typo :)

2024-06-07 10:47 UTC, 0xNilesh commented on test/PushCore/unit_tests/ChannelCreationPush/ChannelMigration.t.sol
> +    function test_migration() external {
The name could be improved: test_ChannelsState_Migration

2024-06-07 10:47 UTC, 0xNilesh commented on test/PushCore/unit_tests/ChannelCreationPush/ChannelMigration.t.sol
> +    function test_ProtocolPoolFeesCorrectForMultipleChannelsCreation()
The name could be improved here as well: test_ProtocolPoolFees_IsCorrect_ForMultipleChannelsCreation

2024-06-07 11:58 UTC, 0xNilesh approved these changes

2024-06-07 12:00 UTC, 0xNilesh requested changes

2024-06-07 12:00 UTC, 0xNilesh commented on test/PushCore/unit_tests/ChannelCreationPush/ChannelMigration.t.sol
> +        coreV3.migaretAddresToBytes32(_channels);
this is remaining @Zartaj0

2024-06-11 07:57 UTC, 0xNilesh approved these changes

2024-06-11 10:02 UTC, zaryab2000 approved these changes
Approving the PR LGTM

Just made one change to shift ChannelMigration test to its own folder, to maintain the structure of the test files. @Zartaj0

2024-06-11 10:03 UTC, merged